#!/bin/bash

declare DOTFILES_DIR_PATH="$(dirname $(dirname $(readlink $BASH_SOURCE)))"

source "$DOTFILES_DIR_PATH/os/utils.sh"

# ----------------------------------------------------------------------

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q='exit'
alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias e='vim'
alias s='subl'
alias g='git'
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias ll='ls -l'
alias m='man'
alias map='xargs -n1'
alias n='npm'
alias q='exit'
alias rm='rm -rf'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases

source "$DOTFILES_DIR_PATH/shell/ubuntu/bash_aliases"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
