#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

declare DOTFILES_DIR_PATH="$(dirname $(dirname $(readlink $BASH_SOURCE)))"

source "$DOTFILES_DIR_PATH/os/utils.sh"

# ----------------------------------------------------------------------

# Enable programmable completion features
# http://tldp.org/LDP/abs/html/tabexpansion.html

source "$DOTFILES_DIR_PATH/shell/ubuntu/bash_autocomplete"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

[ -f "$NVM_DIR/bash_completion" ] \
    && source $NVM_DIR/bash_completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset DOTFILES_DIR_PATH
